### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by pmnlla** [jbrot/jstris-ai#2]
When i try to run `stack build` in the directory with the cloned repo, it tells me I have missing C Libraries. I installed the entire Haskell Platform so I can have Cabal and GHC as well, but it made no difference even after i ran stack build with the `--extra-lib-dirs=c:\clibs`, to point it to where my library DLLs are.
Here is the output:
```
Stack has not been tested with GHC versions above 8.6, and using 8.8.1, this may fail
Stack has not been tested with Cabal versions above 2.4, but version 3.0.0.0 was found, this may fail
hmatrix  > configure
hmatrix  > Configuring hmatrix-0.20.0.0...
hmatrix  > Cabal-simple_Z6RU0evB_3.0.0.0_ghc-8.8.1.exe: Missing dependencies on foreign
hmatrix  > libraries:
hmatrix  > * Missing (or bad) C libraries: blas, lapack
hmatrix  > This problem can usually be solved by installing the system packages that
hmatrix  > provide these libraries (you may need the "-dev" versions). If the libraries
hmatrix  > are already installed but in a non-standard location then you can use the
hmatrix  > flags --extra-include-dirs= and --extra-lib-dirs= to specify where they are.If
hmatrix  > the library files do exist, it may contain errors that are caught by the C
hmatrix  > compiler at the preprocessing stage. In this case you can re-run configure
hmatrix  > with the verbosity flag -v3 to see the error messages.
hmatrix  >

--  While building package hmatrix-0.20.0.0 using:
      C:\sr\setup-exe-cache\x86_64-windows\Cabal-simple_Z6RU0evB_3.0.0.0_ghc-8.8.1.exe --builddir=.stack-work\dist\c9315887 configure --user --package-db=clear --package-db=global --package-db=C:\sr\snapshots\8c619009\pkgdb --libdir=C:\sr\snapshots\8c619009\lib --bindir=C:\sr\snapshots\8c619009\bin --datadir=C:\sr\snapshots\8c619009\share --libexecdir=C:\sr\snapshots\8c619009\libexec --sysconfdir=C:\sr\snapshots\8c619009\etc --docdir=C:\sr\snapshots\8c619009\doc\hmatrix-0.20.0.0 --htmldir=C:\sr\snapshots\8c619009\doc\hmatrix-0.20.0.0 --haddockdir=C:\sr\snapshots\8c619009\doc\hmatrix-0.20.0.0 --dependency=array=array-0.5.4.0 --dependency=base=base-4.13.0.0 --dependency=binary=binary-0.8.7.0 --dependency=bytestring=bytestring-0.10.9.0 --dependency=deepseq=deepseq-1.4.4.0 --dependency=random=random-1.1-CUqV1zxrwrE4K5XCdTZSYy --dependency=semigroups=semigroups-0.19.1-KswQSjRjA2JDrzoYmnhZUy --dependency=split=split-0.2.3.3-J342txBmLbPBICD4Wp49bZ --dependency=storable-complex=storable-complex-0.2.3.0-BQwXL9GlRysCiOi7GlrC9N --dependency=vector=vector-0.12.0.3-3rAYgdX4S5EJIxiT2bfL32 -f-disable-default-paths -f-openblas --extra-include-dirs=C:\Users\Itai\AppData\Local\Programs\stack\x86_64-windows\msys2-20180531\mingw64\include --extra-lib-dirs=C:\Users\Itai\AppData\Local\Programs\stack\x86_64-windows\msys2-20180531\mingw64\lib --extra-lib-dirs=C:\Users\Itai\AppData\Local\Programs\stack\x86_64-windows\msys2-20180531\mingw64\bin --exact-configuration --ghc-option=-fhide-source-paths
    Process exited with code: ExitFailure 1```

**Comment by jbrot** [comment]
You didn't need to install the Haskell Platform. Stack automatically installs the correct copy of GHC, which includes Cabal with it. blas and lapack are C libraries, not Haskell libraries, so you need to install them yourself. On macOS/linux, you would use your package manager to install them. As far as I know, there is not an analogous package manager for Windows, so you will want to build those libraries directly. You can find instructions about this [here](http://icl.cs.utk.edu/lapack-for-windows/lapack/).

However, I recommend you try and build the project from  the [profile branch](https://github.com/jbrot/jstris-ai/tree/profile). The AI is a little better there, and it does not require the blas/lapack dependencies. Note that the profile branch does not have the nice command line interface that the master branch has. The profile branch has the URL the program connects to hard coded in [app/Main.hs](https://github.com/jbrot/jstris-ai/blob/profile/app/Main.hs#L106). You may need to edit that URL depending on where you want the AI to connect.

**Comment by pmnlla** [comment]
Thanks! If i have any further issues while trying to build this, I'll try to use MacOS or Linux before I open a new issue, as I am using a mac running bootcamp after all.
You might want to add this to your readme, but no pressure :)
Thank you!

**Comment by pmnlla** [comment]
I tried again in MacOS and it works! I used the Homebrew package manager to the the `gmp` package because for some reason it's different for macOS. Place the Selenium Driver at `/usr/local/bin/`, and use java SE Dev v13.
